- .github/workflows/pages.yml
- .github/workflows/release.yml
This PR ensures that the `release.yml` and the `pages.yml` actions check out to the `release` branch. This doesn't happen automatically because the actions are triggered from a workflow instead of an `on: push` event, so it defaults to the main branch.
Documentation: https://github.com/actions/checkout
> chore(gh-actions): Fix checkout actions ref branch

- .github/workflows/release.yml
- package.json
- yarn.lock
This PR removes `cycjimmy/semantic-release-action@v3` action due to a bug where the branch where the release happens is mistaken for the repository's main branch:
https://github.com/cycjimmy/semantic-release-action/issues/119
> chore(gh-actions): Remove cycjimmy/semantic-release-action@v3 action

- README.md
- src/lib/Assertion.ts
- src/lib/FunctionAssertion.ts
- src/lib/ObjectAssertion.ts
- test/lib/Assertion.test.ts
This PR add a `.toBeInstanceOf(Constructor)` matcher to the the base `Assertion<T>` class.
> feat(assertion): Add `.toBeInstanceOf(Constructor)` matcher

- src/lib/Assertion.ts
- test/lib/Assertion.test.ts
> feat(assertion): Add .toBeUndefined() matcher

- src/lib/FunctionAssertion.ts
- test/lib/FunctionAssertion.test.ts
Add an overload to the `.toThrow()` matcher so we can match against an error instance directly. The errors are strictly compared.
> feat(function-assertion): Add .toThrow(Error) overload

- src/index.ts
- test/index.test.ts
- test/lib/ArrayAssertion.test.ts
- test/lib/expect.test.ts
This PR fixes some export issues in the entry point of the library:
- Re-export `TypeFactories` and its types to make clearer the exposure on the API
- Remove the default export of `expect`. Now the library exports more than just the `expect` function in its entry point, so it doesn't make sense to make `expect` the default. Will add the default export again if it makes sense or if we get feedback in the future
> fix(core): Export TypeFactories and remove default export

- examples/jest/README.md
- examples/jest/jest.config.js
- examples/jest/package.json
- examples/jest/src/mathUtils.ts
- examples/jest/tests/mathUtils.test.ts
- examples/jest/tsconfig.json
- examples/mocha/.mocharc.json
- examples/mocha/README.md
- examples/mocha/package.json
- examples/mocha/src/mathUtils.ts
- examples/mocha/tests/mathUtils.test.ts
- examples/mocha/tsconfig.json
- package.json
- tsconfig.json
- tslint.json
- yarn.lock
This PR adds minimal example projects for Jest and Mocha, solving issue #63 .
Some details:
- The examples resolve the `assertive-ts` depdendency by using [Yarn workspaces](https://yarnpkg.com/features/workspaces). I based this on how examples are set up in [Jest's source code](https://github.com/facebook/jest). This required adding a `workspaces` field to the top level `package.json` file. Please tell me if I should use another approach.
- I followed the instructions from the documentation as they are. That's why there are two `tsconfig.json` files with a lot of commented-out fields (generated by `npx tsc -init`).
> docs: Example projects

- src/lib/DateAssertion.ts
- src/lib/helpers/dates.ts
- test/lib/DateAssertion.test.ts
This PR fixes #75 . I chose this implementation so the `.toBeDayOfWeek` matcher's behavior is consistent with Javascript's `Date.getDay` and with `.toBeDayOfWeek`'s documentation. I also changed its docs so it's clear what a number literal means when using the matcher.
I also think there should be a `.toBeISODayOfWeek` matcher, to avoid further confusion.
- Add a test that exposes the issue.
- Change convertion of "sunday" to 0 instead of 7.
- Improve `.toBeDayOfWeek` docs.
> Fix: DateAssertion.toBeDayOfWeek when using "sunday"

- src/lib/DateAssertion.ts
- test/lib/DateAssertion.test.ts
Ths PR fixes #77 .  The issue was that the `DateAssertion.toMatchDateParts` was checking the actual date's fields with the exact fields from the options, instead of the fields of *the date* generated by the options.
A test that exposes the bug was also added.
> Fix: DateAssertion.toMatchDateParts when using month literals (#77)

- packages/core/src/lib/helpers/TypeFactories.ts
This PR corrects the types of the `TypeFactories.instanceOf(..)` helper. The issue was that the assertion factory was creating an assertion for the constructor instead of the instance. Using the alias `Constructor<T>` instead resolves the issue as the assertion factory will create an instance for `T` instead.
**Example:**
```ts
class Car {
private model: string;
constructor(model: string) {
this.mode = model;
}
}
expect(value)
.asType(TypeFactories.instanceOf(Car))
.toBeEqual(new Car("Porsche 911"));
```
> fix(type-factories): Correct types on instanceOf type factory

- package/src/lib/DateAssertion.ts
- package/src/lib/DateAssertion.types.ts
- package/src/lib/helpers/dates.ts
- package/test/lib/DateAssertion.test.ts
- package/test/lib/helpers/dates.test.ts
This Pr fixes a few inconsistencies with the `.toMatchDateParts(..)` method of the `DateAssertion` class.
- The `optionsToDate(..)` helper should not use today's date to fill up the missing options. Using today's date causes inconsistencies around the date comparison whenever the current date is around the edges of the local time offset. I.e., today transforms into tomorrow because of the timezone change, which causes a different behavior.
- The AssertionError message should compare the date with the options provided to clarify the assertion issue. Comparing only the two date was ambiguous for this assertion.
> fix(date-assertion): Solve .toMatchDateParts inconsistencies

- package/src/lib/ObjectAssertion.ts
- package/test/lib/ObjectAssertion.test.ts
This PR updates most of the `ObjectAssertion` matches to use variadic parameters. It also updates the `AssertionError` options so we can show diffs when the assertion fails, providing more complete information to the user.
> feat(object-assertion): Matchers use variadic arguments

- package/package.json
- package/src/lib/ArrayAssertion.ts
- package/src/lib/Assertion.ts
- package/src/lib/FunctionAssertion.ts
- package/src/lib/ObjectAssertion.ts
- package/src/lib/PromiseAssertion.ts
- yarn.lock
This PR changes the depp equality comparator from the default node to the faster [fast-deep-equal](https://github.com/epoberezkin/fast-deep-equal) so we can have increased performance on big deep objects.
> feat(equallity): Use fast-deep-equal for faster deep equallity

- package/src/lib/Assertion.ts
- package/test/lib/Assertion.test.ts
This PR adds a missing matcher on the `Assertion` base class based on the `typeof` operator
> feat(assertion): Add typeof based matcher

- package/src/lib/ObjectAssertion.ts
- package/test/lib/ObjectAssertion.test.ts
> feat(object): Add .toHave[Keys|Values|Entries] methods

- .github/workflows/release.yml
- package.json
- package/.npmrc
- package/.releaserc.json
- package/package.json
- turbo.json
- yarn.lock
This PR changes the release workflow to use the [semantic-release-yarn](https://github.com/hongaar/semantic-release-yarn) plugin instead of the usual `@semantic-release/npm` to publish the package. The new plugin is intended to publish using Yarn 2.0+ while supporting workspaces for monorepo project structures.
> chore(release): Use semantic-release-yarn to support monorepos

- packages/core/src/lib/Assertion.ts
- packages/core/test/lib/Assertion.test.ts
Include `toBeSameAs` and `toBe` alias for `toBeSame`.
*NOTE:* My code formatter modified some files. Let me know if it's okay to keep it that way, otherwise I can revert that to keep only the necessary changes.﻿
Solves #108 
---
As part of [Stack Builders Inc.](https://www.stackbuilders.com/) Hacktoberfest 2023 event.
> feat: Include aliases toBeSameAs and toBe for toBeSame

- README.md
I have added some missing assertion examples to the README, this will help anyone who wants to use the library, to easily find a good use case.
Let me know what you think.
> docs(readme): Add missing examples

- packages/core/src/index.ts
- packages/core/src/lib/config/Config.ts
Some plugins might consist of multiple assertion instances. These plugins might want to expose a single variable to be used by the `usePlugin(..)` function, so we need the argument so accept a single plugin (for backward compact) or an array of them.
> fix(core): Allow arrays of plugins on usePlugin(..)

- examples/jest/package.json
- examples/mocha/package.json
- package.json
- packages/README.md
- packages/sinon/.mocharc.json
- packages/sinon/.releaserc.json
- packages/sinon/README.md
- packages/sinon/package.json
- packages/sinon/src/lib/SinonSpyAssertion.ts
- packages/sinon/src/lib/SinonSpyCallAssertion.ts
- packages/sinon/src/lib/helpers/messages.ts
- packages/sinon/src/main.ts
- packages/sinon/test/helpers/common.ts
- packages/sinon/test/hooks.ts
- packages/sinon/test/unit/lib/SinonSpyAssertion.test.ts
- packages/sinon/test/unit/lib/SinonSpyCallAssertion.test.ts
- packages/sinon/test/unit/lib/helpers/messages.test.ts
- packages/sinon/test/unit/main.test.ts
- packages/sinon/tsconfig.json
- packages/sinon/tsconfig.prod.json
- packages/sinon/typedoc.json
- yarn.lock
An Assertive.ts plugin to match over [Sinon.js](https://sinonjs.org/) spies, stubs, mocks, and fakes. Check the README.md for details on usage and how it should look like 🙂
> feat(sinon): Add @assertive-ts/sinon plugin

- package.json
- packages/core/.mocharc.json
- packages/core/.releaserc.json
- packages/sinon/.mocharc.json
- packages/sinon/.releaserc.json
- turbo.json
Fix the main script to run the `docs` command using turbo so all docs are generated on deploy.
> chore(all): Use turbo to build all docs

- README.md
- docs/development.md
- packages/core/.releaserc.json
- packages/dom/.releaserc.json
- packages/sinon/.releaserc.json
Adding the scope `all` to all packages allows us to push commits that can cause a release in all packages.
> chore(all): Allow scope `all` for all packages

- examples/jest/package.json
- examples/mocha/package.json
- examples/symbolPlugin/package.json
- package.json
- packages/core/package.json
- packages/dom/package.json
- packages/sinon/package.json
- yarn.lock
Because the base TypeScript configuration has `"importHelpers": true`, we must ensure that `tslib` is available at runtime in all packages. Additionally, to use the latest version of `tslib`, TypeScript, ESLint, and their TS plugins were also updated.
https://zenzes.me/today-i-learned-tslib-is-not-a-devdependency/
> fix(all): Add tslib dependency

- packages/core/src/lib/helpers/TypeFactories.ts
- packages/core/test/lib/helpers/TypeFactories.test.ts
Add `Factories.Error` and `Factories.error(..)` helpers so assertion instances can be converted into `ErrorAssertion<T>`
> feat(core): Error type factories

- README.md
Remove mentions of browser, per discussion in #141
> Remove browser support from README

- packages/dom/src/lib/ElementAssertion.ts
- packages/dom/test/unit/lib/ElementAssertion.test.tsx
- packages/dom/test/unit/lib/fixtures/haveClassTestComponent.tsx
Added the toHaveClass matcher.
> feat(dom): Add toHaveClass , toHaveAllClasses, and toHaveAnyClass assertions

- packages/native/src/lib/ElementAssertion.ts
- packages/native/test/lib/ElementAssertion.test.tsx
This PR adds the `toBeVisible` matcher for React Native
> feat(native): Add toBeVisible
